{% set name = "anaconda-ai" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anaconda_ai-{{ version }}.tar.gz
  sha256: 0506f378a8a46d85ccaa4c10db2d22fd1180f9179c87980b43979923eaf73818

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >={{ python_min }}
    - anaconda-auth >=0.8
    - anaconda-cli-base >=0.5
    - rich
    - pydantic >=2
    - typer
    - ruamel.yaml
    - openai
    - platformdirs
    - packaging
    - click <8.2
    - ruamel_yaml
  run_constrained:
    - langchain-openai >=0.2.8
    - llm >=0.22

test:
  imports:
    - anaconda_ai
    - anaconda_ai.cli
    - anaconda_ai.clients
    - anaconda_ai.config
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Download, launch, and integrate AI models curated by Anaconda
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://anaconda.cloud

extra:
  recipe-maintainers:
    - AlbertDeFusco
    - nbeerbower
